/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#1e293b",
        "primary-fixed": "#e0e7ff",
        "on-primary-fixed-variant": "#312e81",
        "surface-variant": "#e2e8f0",
        "error-dim": "#7f1d1d",
        "on-tertiary-fixed": "#1e293b",
        "on-tertiary": "#f1f5f9",
        "tertiary-fixed": "#e0e7ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#cbd5e1",
        "on-tertiary-container": "#1e293b",
        "on-tertiary-fixed-variant": "#334155",
        "inverse-primary": "#c7d2fe",
        tertiary: "#6366f1",
        "on-primary-fixed": "#1e1b4b",
        "surface-container-highest": "#cbd5e1",
        "outline-variant": "#cbd5e1",
        "secondary-container": "#e0e7ff",
        "on-secondary-fixed": "#1e1b4b",
        "on-secondary-container": "#312e81",
        "inverse-surface": "#0f172a",
        "on-secondary-fixed-variant": "#3730a3",
        "surface-tint": "#1e1b4b",
        "surface-dim": "#e2e8f0",
        "on-error-container": "#7f1d1d",
        "surface-container-low": "#f8fafc",
        primary: "#1e1b4b",
        "surface-container-high": "#f1f5f9",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        background: "#f8fafc",
        "primary-container": "#e0e7ff",
        "tertiary-fixed-dim": "#c7d2fe",
        "on-surface-variant": "#475569",
        "inverse-on-surface": "#94a3b8",
        "surface-container": "#f1f5f9",
        outline: "#64748b",
        surface: "#f8fafc",
        error: "#ef4444",
        "on-background": "#0f172a",
        "secondary-fixed": "#e0e7ff",
        "on-surface": "#0f172a",
        "primary-fixed-dim": "#c7d2fe",
        "on-primary-container": "#1e1b4b",
        secondary: "#a5b4fc",
        "error-container": "#fee2e2",
        "tertiary-dim": "#4f46e5",
        "surface-bright": "#f8fafc",
        "primary-dim": "#1e1b4b",
        "secondary-dim": "#818cf8",
        "tertiary-container": "#e0e7ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
      fontFamily: {
        headline: ["Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
        body: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        label: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
